apiVersion: v1
kind: Deployment
metadata:
  name: sanic
  labels:
    name: sanic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sanic
    spec:
      containers:
      - name: sanic
        image: sanic:latest
        env:
        - name: SANIC_CONFIG
          value: "development"
      restartPolicy: Always